export type CatalogKind = "stable" | "catalog" | "chart" | "provider";

export type CatalogCategory = "component" | "chart" | "block";

export interface CatalogEntry {
	slug: string;
	name: string;
	exportName: string;
	importPath: string;
	hasRootBarrel: boolean;
	kind: CatalogKind;
	category: CatalogCategory;
	navName?: string;
}

export const CATALOG_CATEGORIES: { id: CatalogCategory; label: string }[] = [
	{ id: "component", label: "Components" },
	{ id: "chart", label: "Charts" },
	{ id: "block", label: "Blocks" },
];

export const CATALOG: CatalogEntry[] = [
	{
		slug: "button",
		name: "Button",
		exportName: "Button",
		importPath: "@nocoo/basalt/components/button",
		hasRootBarrel: true,
		kind: "stable",
		category: "component",
	},
	{
		slug: "link-button",
		name: "LinkButton",
		exportName: "LinkButton",
		importPath: "@nocoo/basalt/components/button",
		hasRootBarrel: false,
		kind: "catalog",
		category: "component",
	},
	{
		slug: "text",
		name: "Text",
		exportName: "Text",
		importPath: "@nocoo/basalt/components/text",
		hasRootBarrel: true,
		kind: "stable",
		category: "component",
	},
	{
		slug: "label",
		name: "Label",
		exportName: "Label",
		importPath: "@nocoo/basalt/components/label",
		hasRootBarrel: true,
		kind: "stable",
		category: "component",
	},
	{
		slug: "separator",
		name: "Separator",
		exportName: "Separator",
		importPath: "@nocoo/basalt/components/separator",
		hasRootBarrel: true,
		kind: "stable",
		category: "component",
	},
	{
		slug: "scroll-area",
		name: "ScrollArea",
		exportName: "ScrollArea",
		importPath: "@nocoo/basalt/components/scroll-area",
		hasRootBarrel: true,
		kind: "stable",
		category: "component",
		navName: "Scroll Area",
	},
	{
		slug: "link",
		name: "Link",
		exportName: "Link",
		importPath: "@nocoo/basalt/components/link",
		hasRootBarrel: true,
		kind: "stable",
		category: "component",
	},
	{
		slug: "tooltip",
		name: "Tooltip",
		exportName: "Tooltip",
		importPath: "@nocoo/basalt/components/tooltip",
		hasRootBarrel: true,
		kind: "stable",
		category: "component",
	},
	{
		slug: "theme-toggle",
		name: "ThemeToggle",
		exportName: "ThemeToggle",
		importPath: "@nocoo/basalt/components/theme-toggle",
		hasRootBarrel: true,
		kind: "stable",
		category: "component",
	},
	{
		slug: "layer-card",
		name: "LayerCard",
		exportName: "LayerCard",
		importPath: "@nocoo/basalt/components/layer-card",
		hasRootBarrel: true,
		kind: "stable",
		category: "component",
		navName: "Layer Card",
	},
	{
		slug: "description-list",
		name: "DescriptionList",
		exportName: "DescriptionList",
		importPath: "@nocoo/basalt/components/description-list",
		hasRootBarrel: true,
		kind: "catalog",
		category: "component",
		navName: "Description List",
	},
	{
		slug: "basalt-mark",
		name: "BasaltMark",
		exportName: "BasaltMark",
		importPath: "@nocoo/basalt/components/basalt-mark",
		hasRootBarrel: false,
		kind: "catalog",
		category: "component",
		navName: "Basalt Mark",
	},
	{
		slug: "field",
		name: "Field",
		exportName: "Field",
		importPath: "@nocoo/basalt/components/field",
		hasRootBarrel: true,
		kind: "stable",
		category: "component",
	},
	{
		slug: "input",
		name: "Input",
		exportName: "Input",
		importPath: "@nocoo/basalt/components/input",
		hasRootBarrel: true,
		kind: "stable",
		category: "component",
	},
	{
		slug: "input-area",
		name: "InputArea",
		exportName: "InputArea",
		importPath: "@nocoo/basalt/components/input-area",
		hasRootBarrel: false,
		kind: "catalog",
		category: "component",
	},
	{
		slug: "input-group",
		name: "InputGroup",
		exportName: "InputGroup",
		importPath: "@nocoo/basalt/components/input-group",
		hasRootBarrel: false,
		kind: "catalog",
		category: "component",
	},
	{
		slug: "sensitive-input",
		name: "SensitiveInput",
		exportName: "SensitiveInput",
		importPath: "@nocoo/basalt/components/sensitive-input",
		hasRootBarrel: false,
		kind: "catalog",
		category: "component",
		navName: "Sensitive Input",
	},
	{
		slug: "checkbox",
		name: "Checkbox",
		exportName: "Checkbox",
		importPath: "@nocoo/basalt/components/checkbox",
		hasRootBarrel: true,
		kind: "stable",
		category: "component",
	},
	{
		slug: "radio",
		name: "Radio",
		exportName: "Radio",
		importPath: "@nocoo/basalt/components/radio",
		hasRootBarrel: false,
		kind: "catalog",
		category: "component",
	},
	{
		slug: "switch",
		name: "Switch",
		exportName: "Switch",
		importPath: "@nocoo/basalt/components/switch",
		hasRootBarrel: true,
		kind: "stable",
		category: "component",
	},
	{
		slug: "select",
		name: "Select",
		exportName: "Select",
		importPath: "@nocoo/basalt/components/select",
		hasRootBarrel: false,
		kind: "catalog",
		category: "component",
	},
	{
		slug: "combobox",
		name: "Combobox",
		exportName: "Combobox",
		importPath: "@nocoo/basalt/components/combobox",
		hasRootBarrel: false,
		kind: "catalog",
		category: "component",
	},
	{
		slug: "autocomplete",
		name: "Autocomplete",
		exportName: "Autocomplete",
		importPath: "@nocoo/basalt/components/autocomplete",
		hasRootBarrel: false,
		kind: "catalog",
		category: "component",
	},
	{
		slug: "date-picker",
		name: "DatePicker",
		exportName: "DatePicker",
		importPath: "@nocoo/basalt/components/date-picker",
		hasRootBarrel: false,
		kind: "catalog",
		category: "component",
		navName: "Date Picker",
	},
	{
		slug: "slider",
		name: "Slider",
		exportName: "Slider",
		importPath: "@nocoo/basalt/components/slider",
		hasRootBarrel: false,
		kind: "catalog",
		category: "component",
	},
	{
		slug: "toggle",
		name: "Toggle",
		exportName: "Toggle",
		importPath: "@nocoo/basalt/components/toggle",
		hasRootBarrel: false,
		kind: "catalog",
		category: "component",
	},
	{
		slug: "toggle-group",
		name: "ToggleGroup",
		exportName: "ToggleGroup",
		importPath: "@nocoo/basalt/components/toggle-group",
		hasRootBarrel: false,
		kind: "catalog",
		category: "component",
	},
	{
		slug: "segment-control",
		name: "SegmentControl",
		exportName: "SegmentControl",
		importPath: "@nocoo/basalt/components/segment-control",
		hasRootBarrel: true,
		kind: "stable",
		category: "component",
		navName: "Segment Control",
	},
	{
		slug: "badge",
		name: "Badge",
		exportName: "Badge",
		importPath: "@nocoo/basalt/components/badge",
		hasRootBarrel: true,
		kind: "stable",
		category: "component",
	},
	{
		slug: "banner",
		name: "Banner",
		exportName: "Banner",
		importPath: "@nocoo/basalt/components/banner",
		hasRootBarrel: false,
		kind: "catalog",
		category: "component",
	},
	{
		slug: "empty",
		name: "Empty",
		exportName: "Empty",
		importPath: "@nocoo/basalt/components/empty",
		hasRootBarrel: false,
		kind: "catalog",
		category: "component",
	},
	{
		slug: "loader",
		name: "Loader",
		exportName: "Loader",
		importPath: "@nocoo/basalt/components/loader",
		hasRootBarrel: false,
		kind: "catalog",
		category: "component",
	},
	{
		slug: "skeleton-line",
		name: "SkeletonLine",
		exportName: "SkeletonLine",
		importPath: "@nocoo/basalt/components/skeleton-line",
		hasRootBarrel: false,
		kind: "catalog",
		category: "component",
		navName: "Skeleton Line",
	},
	{
		slug: "battery-meter",
		name: "BatteryMeter",
		exportName: "BatteryMeter",
		importPath: "@nocoo/basalt/components/battery-meter",
		hasRootBarrel: false,
		kind: "catalog",
		category: "component",
	},
	{
		slug: "meter",
		name: "Meter",
		exportName: "Meter",
		importPath: "@nocoo/basalt/components/meter",
		hasRootBarrel: true,
		kind: "stable",
		category: "component",
	},
	{
		slug: "toast",
		name: "Toast",
		exportName: "Toast",
		importPath: "@nocoo/basalt/components/toast",
		hasRootBarrel: true,
		kind: "stable",
		category: "component",
	},
	{
		slug: "clipboard-text",
		name: "ClipboardText",
		exportName: "ClipboardText",
		importPath: "@nocoo/basalt/components/clipboard-text",
		hasRootBarrel: false,
		kind: "catalog",
		category: "component",
		navName: "Clipboard Text",
	},
	{
		slug: "code",
		name: "Code",
		exportName: "Code",
		importPath: "@nocoo/basalt/components/code",
		hasRootBarrel: false,
		kind: "catalog",
		category: "component",
		navName: "CodeHighlighted",
	},
	{
		slug: "code-block",
		name: "CodeBlock",
		exportName: "CodeBlock",
		importPath: "@nocoo/basalt/components/code",
		hasRootBarrel: false,
		kind: "catalog",
		category: "component",
	},
	{
		slug: "avatar",
		name: "Avatar",
		exportName: "Avatar",
		importPath: "@nocoo/basalt/components/avatar",
		hasRootBarrel: true,
		kind: "stable",
		category: "component",
	},
	{
		slug: "accordion",
		name: "Accordion",
		exportName: "Accordion",
		importPath: "@nocoo/basalt/components/accordion",
		hasRootBarrel: false,
		kind: "catalog",
		category: "component",
	},
	{
		slug: "dialog",
		name: "Dialog",
		exportName: "Dialog",
		importPath: "@nocoo/basalt/components/dialog",
		hasRootBarrel: true,
		kind: "stable",
		category: "component",
	},
	{
		slug: "alert-dialog",
		name: "AlertDialog",
		exportName: "AlertDialog",
		importPath: "@nocoo/basalt/components/alert-dialog",
		hasRootBarrel: true,
		kind: "stable",
		category: "component",
	},
	{
		slug: "confirm-dialog",
		name: "ConfirmDialog",
		exportName: "ConfirmDialog",
		importPath: "@nocoo/basalt/components/confirm-dialog",
		hasRootBarrel: true,
		kind: "stable",
		category: "component",
		navName: "Confirm Dialog",
	},
	{
		slug: "popover",
		name: "Popover",
		exportName: "Popover",
		importPath: "@nocoo/basalt/components/popover",
		hasRootBarrel: true,
		kind: "stable",
		category: "component",
	},
	{
		slug: "dropdown-menu",
		name: "DropdownMenu",
		exportName: "DropdownMenu",
		importPath: "@nocoo/basalt/components/dropdown-menu",
		hasRootBarrel: true,
		kind: "stable",
		category: "component",
		navName: "Dropdown",
	},
	{
		slug: "context-menu",
		name: "ContextMenu",
		exportName: "ContextMenu",
		importPath: "@nocoo/basalt/components/context-menu",
		hasRootBarrel: false,
		kind: "catalog",
		category: "component",
	},
	{
		slug: "hover-card",
		name: "HoverCard",
		exportName: "HoverCard",
		importPath: "@nocoo/basalt/components/hover-card",
		hasRootBarrel: false,
		kind: "catalog",
		category: "component",
	},
	{
		slug: "sheet",
		name: "Sheet",
		exportName: "Sheet",
		importPath: "@nocoo/basalt/components/sheet",
		hasRootBarrel: true,
		kind: "stable",
		category: "component",
	},
	{
		slug: "command-palette",
		name: "CommandPalette",
		exportName: "CommandPalette",
		importPath: "@nocoo/basalt/components/command-palette",
		hasRootBarrel: true,
		kind: "stable",
		category: "component",
		navName: "Command Palette",
	},
	{
		slug: "tabs",
		name: "Tabs",
		exportName: "Tabs",
		importPath: "@nocoo/basalt/components/tabs",
		hasRootBarrel: true,
		kind: "stable",
		category: "component",
	},
	{
		slug: "table",
		name: "Table",
		exportName: "Table",
		importPath: "@nocoo/basalt/components/table",
		hasRootBarrel: false,
		kind: "catalog",
		category: "component",
	},
	{
		slug: "data-table",
		name: "DataTable",
		exportName: "DataTable",
		importPath: "@nocoo/basalt/components/data-table",
		hasRootBarrel: false,
		kind: "catalog",
		category: "component",
	},
	{
		slug: "pagination",
		name: "Pagination",
		exportName: "Pagination",
		importPath: "@nocoo/basalt/components/pagination",
		hasRootBarrel: false,
		kind: "catalog",
		category: "component",
	},
	{
		slug: "collapsible",
		name: "Collapsible",
		exportName: "Collapsible",
		importPath: "@nocoo/basalt/components/collapsible",
		hasRootBarrel: true,
		kind: "stable",
		category: "component",
	},
	{
		slug: "breadcrumbs",
		name: "Breadcrumbs",
		exportName: "Breadcrumbs",
		importPath: "@nocoo/basalt/components/breadcrumbs",
		hasRootBarrel: false,
		kind: "catalog",
		category: "component",
	},
	{
		slug: "navigation-menu",
		name: "NavigationMenu",
		exportName: "NavigationMenu",
		importPath: "@nocoo/basalt/components/navigation-menu",
		hasRootBarrel: false,
		kind: "catalog",
		category: "component",
	},
	{
		slug: "menu-bar",
		name: "MenuBar",
		exportName: "MenuBar",
		importPath: "@nocoo/basalt/components/menu-bar",
		hasRootBarrel: false,
		kind: "catalog",
		category: "component",
	},
	{
		slug: "toolbar",
		name: "Toolbar",
		exportName: "Toolbar",
		importPath: "@nocoo/basalt/components/toolbar",
		hasRootBarrel: true,
		kind: "catalog",
		category: "component",
	},
	{
		slug: "table-of-contents",
		name: "TableOfContents",
		exportName: "TableOfContents",
		importPath: "@nocoo/basalt/components/table-of-contents",
		hasRootBarrel: false,
		kind: "catalog",
		category: "component",
		navName: "Table of Contents",
	},
	{
		slug: "grid",
		name: "Grid",
		exportName: "Grid",
		importPath: "@nocoo/basalt/components/grid",
		hasRootBarrel: false,
		kind: "catalog",
		category: "component",
	},
	{
		slug: "section-rule",
		name: "SectionRule",
		exportName: "SectionRule",
		importPath: "@nocoo/basalt/components/section-rule",
		hasRootBarrel: false,
		kind: "catalog",
		category: "component",
		navName: "Section Rule",
	},
	{
		slug: "sidebar",
		name: "Sidebar",
		exportName: "Sidebar",
		importPath: "@nocoo/basalt/components/sidebar",
		hasRootBarrel: true,
		kind: "stable",
		category: "component",
	},
	{
		slug: "flow",
		name: "Flow",
		exportName: "Flow",
		importPath: "@nocoo/basalt/components/flow",
		hasRootBarrel: false,
		kind: "catalog",
		category: "component",
	},
	{
		slug: "stat-strip",
		name: "StatStrip",
		exportName: "StatStrip",
		importPath: "@nocoo/basalt/components/stat-strip",
		hasRootBarrel: true,
		kind: "stable",
		category: "component",
		navName: "Stat Strip",
	},
	{
		slug: "table-pager",
		name: "TablePager",
		exportName: "TablePager",
		importPath: "@nocoo/basalt/components/table-pager",
		hasRootBarrel: true,
		kind: "stable",
		category: "component",
		navName: "Table Pager",
	},
	{
		slug: "fab",
		name: "Fab",
		exportName: "Fab",
		importPath: "@nocoo/basalt/components/fab",
		hasRootBarrel: false,
		kind: "catalog",
		category: "component",
	},
	{
		slug: "dock",
		name: "Dock",
		exportName: "Dock",
		importPath: "@nocoo/basalt/components/dock",
		hasRootBarrel: false,
		kind: "catalog",
		category: "component",
	},
	{
		slug: "chat-bubble",
		name: "ChatBubble",
		exportName: "ChatBubble",
		importPath: "@nocoo/basalt/components/chat-bubble",
		hasRootBarrel: false,
		kind: "catalog",
		category: "component",
		navName: "Chat Bubble",
	},
	{
		slug: "chat-composer",
		name: "ChatComposer",
		exportName: "ChatComposer",
		importPath: "@nocoo/basalt/components/chat-composer",
		hasRootBarrel: false,
		kind: "catalog",
		category: "component",
		navName: "Chat Composer",
	},
	{
		slug: "chat-header",
		name: "ChatHeader",
		exportName: "ChatHeader",
		importPath: "@nocoo/basalt/components/chat-header",
		hasRootBarrel: false,
		kind: "catalog",
		category: "component",
		navName: "Chat Header",
	},
	{
		slug: "chat-inbox",
		name: "ChatInbox",
		exportName: "ChatInbox",
		importPath: "@nocoo/basalt/components/chat-inbox",
		hasRootBarrel: false,
		kind: "catalog",
		category: "component",
		navName: "Chat Inbox",
	},
	{
		slug: "theme-provider",
		name: "ThemeProvider",
		exportName: "ThemeProvider",
		importPath: "@nocoo/basalt/providers/theme",
		hasRootBarrel: true,
		kind: "provider",
		category: "component",
	},
	{
		slug: "link-provider",
		name: "LinkProvider",
		exportName: "LinkProvider",
		importPath: "@nocoo/basalt/providers/link",
		hasRootBarrel: true,
		kind: "provider",
		category: "component",
	},
	{
		slug: "multi-select",
		name: "MultiSelect",
		exportName: "MultiSelect",
		importPath: "@nocoo/basalt/components/multi-select",
		hasRootBarrel: false,
		kind: "catalog",
		category: "component",
		navName: "Searchable Multi Select",
	},
	{
		slug: "filter-bar",
		name: "FilterBar",
		exportName: "FilterBar",
		importPath: "@nocoo/basalt/components/filter-bar",
		hasRootBarrel: false,
		kind: "catalog",
		category: "component",
		navName: "Filter Bar",
	},
	{
		slug: "file-dropzone",
		name: "FileDropzone",
		exportName: "FileDropzone",
		importPath: "@nocoo/basalt/components/file-dropzone",
		hasRootBarrel: false,
		kind: "catalog",
		category: "component",
		navName: "File Dropzone",
	},
	{
		slug: "upload-queue",
		name: "UploadQueue",
		exportName: "UploadQueue",
		importPath: "@nocoo/basalt/components/upload-queue",
		hasRootBarrel: false,
		kind: "catalog",
		category: "component",
		navName: "Upload Queue",
	},
	{
		slug: "charts",
		name: "Charts",
		exportName: "Charts",
		importPath: "@nocoo/basalt/charts/charts",
		hasRootBarrel: false,
		kind: "chart",
		category: "chart",
	},
	{
		slug: "chart-colors",
		name: "Colors",
		exportName: "Colors",
		importPath: "@nocoo/basalt/charts/chart-colors",
		hasRootBarrel: false,
		kind: "chart",
		category: "chart",
	},
	{
		slug: "timeseries",
		name: "Timeseries",
		exportName: "Timeseries",
		importPath: "@nocoo/basalt/charts/timeseries",
		hasRootBarrel: false,
		kind: "chart",
		category: "chart",
	},
	{
		slug: "maps",
		name: "Maps",
		exportName: "Maps",
		importPath: "@nocoo/basalt/charts/maps",
		hasRootBarrel: false,
		kind: "chart",
		category: "chart",
	},
	{
		slug: "custom-chart",
		name: "Custom Chart",
		exportName: "CustomChart",
		importPath: "@nocoo/basalt/charts/custom-chart",
		hasRootBarrel: false,
		kind: "chart",
		category: "chart",
	},
	{
		slug: "stat-card",
		name: "StatCard",
		exportName: "StatCard",
		importPath: "@nocoo/basalt/charts/stat-card",
		hasRootBarrel: false,
		kind: "chart",
		category: "chart",
	},
	{
		slug: "slot-bar",
		name: "SlotBarChart",
		exportName: "SlotBarChart",
		importPath: "@nocoo/basalt/charts/slot-bar",
		hasRootBarrel: false,
		kind: "chart",
		category: "chart",
	},
	{
		slug: "bar",
		name: "BarChart",
		exportName: "BarChart",
		importPath: "@nocoo/basalt/charts/bar",
		hasRootBarrel: false,
		kind: "chart",
		category: "chart",
	},
	{
		slug: "line",
		name: "LineChart",
		exportName: "LineChart",
		importPath: "@nocoo/basalt/charts/line",
		hasRootBarrel: false,
		kind: "chart",
		category: "chart",
	},
	{
		slug: "area",
		name: "AreaChart",
		exportName: "AreaChart",
		importPath: "@nocoo/basalt/charts/area",
		hasRootBarrel: false,
		kind: "chart",
		category: "chart",
	},
	{
		slug: "donut",
		name: "DonutChart",
		exportName: "DonutChart",
		importPath: "@nocoo/basalt/charts/donut",
		hasRootBarrel: false,
		kind: "chart",
		category: "chart",
	},
	{
		slug: "grouped-bar",
		name: "GroupedBarChart",
		exportName: "GroupedBarChart",
		importPath: "@nocoo/basalt/charts/grouped-bar",
		hasRootBarrel: false,
		kind: "chart",
		category: "chart",
	},
	{
		slug: "stacked-bar",
		name: "StackedBarChart",
		exportName: "StackedBarChart",
		importPath: "@nocoo/basalt/charts/stacked-bar",
		hasRootBarrel: false,
		kind: "chart",
		category: "chart",
	},
	{
		slug: "sparkline",
		name: "Sparkline",
		exportName: "Sparkline",
		importPath: "@nocoo/basalt/charts/sparkline",
		hasRootBarrel: false,
		kind: "chart",
		category: "chart",
	},
	{
		slug: "heatmap-calendar",
		name: "HeatmapCalendar",
		exportName: "HeatmapCalendar",
		importPath: "@nocoo/basalt/charts/heatmap-calendar",
		hasRootBarrel: false,
		kind: "chart",
		category: "chart",
	},
	{
		slug: "heatmap-matrix",
		name: "HeatmapMatrix",
		exportName: "HeatmapMatrix",
		importPath: "@nocoo/basalt/charts/heatmap-matrix",
		hasRootBarrel: false,
		kind: "chart",
		category: "chart",
	},
	{
		slug: "gauge",
		name: "Gauge",
		exportName: "Gauge",
		importPath: "@nocoo/basalt/charts/gauge",
		hasRootBarrel: false,
		kind: "chart",
		category: "chart",
	},
	{
		slug: "radar",
		name: "RadarChart",
		exportName: "RadarChart",
		importPath: "@nocoo/basalt/charts/radar",
		hasRootBarrel: false,
		kind: "chart",
		category: "chart",
	},
	{
		slug: "funnel",
		name: "FunnelChart",
		exportName: "FunnelChart",
		importPath: "@nocoo/basalt/charts/funnel",
		hasRootBarrel: false,
		kind: "chart",
		category: "chart",
	},
	{
		slug: "bullet",
		name: "BulletChart",
		exportName: "BulletChart",
		importPath: "@nocoo/basalt/charts/bullet",
		hasRootBarrel: false,
		kind: "chart",
		category: "chart",
	},
	{
		slug: "timeline",
		name: "Timeline",
		exportName: "Timeline",
		importPath: "@nocoo/basalt/charts/timeline",
		hasRootBarrel: false,
		kind: "chart",
		category: "chart",
	},
	{
		slug: "sankey",
		name: "SankeyChart",
		exportName: "SankeyChart",
		importPath: "@nocoo/basalt/charts/sankey",
		hasRootBarrel: false,
		kind: "chart",
		category: "chart",
		navName: "Sankey",
	},
	{
		slug: "item-list",
		name: "ItemList",
		exportName: "ItemList",
		importPath: "@nocoo/basalt/charts/item-list",
		hasRootBarrel: false,
		kind: "chart",
		category: "chart",
	},
	{
		slug: "date-navigation",
		name: "DateNavigation",
		exportName: "DateNavigation",
		importPath: "@nocoo/basalt/charts/date-navigation",
		hasRootBarrel: false,
		kind: "chart",
		category: "chart",
	},
	{
		slug: "palette",
		name: "ChartPalette",
		exportName: "ChartPalette",
		importPath: "@nocoo/basalt/charts/palette",
		hasRootBarrel: false,
		kind: "chart",
		category: "chart",
	},
	{
		slug: "page-header",
		name: "Page Header",
		exportName: "PageHeader",
		importPath: "@nocoo/basalt/components/page-header",
		hasRootBarrel: false,
		kind: "catalog",
		category: "block",
	},
	{
		slug: "resource-list",
		name: "Resource List",
		exportName: "ResourceList",
		importPath: "@nocoo/basalt/components/resource-list",
		hasRootBarrel: false,
		kind: "catalog",
		category: "block",
	},
	{
		slug: "delete-resource",
		name: "Delete Resource",
		exportName: "DeleteResource",
		importPath: "@nocoo/basalt/components/delete-resource",
		hasRootBarrel: false,
		kind: "catalog",
		category: "block",
	},
];

export const CATALOG_BY_SLUG = new Map(CATALOG.map((entry) => [entry.slug, entry]));

const CHART_LEAD = ["charts", "chart-colors", "timeseries", "maps", "sankey", "custom-chart"];
const BLOCK_LEAD = ["page-header", "resource-list", "delete-resource"];

export function catalogNavName(entry: CatalogEntry): string {
	return entry.navName ?? entry.name;
}

export function inScopeCatalogSlugs(): string[] {
	return CATALOG.filter(
		(entry) =>
			(entry.category === "component" || entry.category === "chart") && entry.slug !== "maps",
	).map((entry) => entry.slug);
}

function byNavName(a: CatalogEntry, b: CatalogEntry) {
	return catalogNavName(a).localeCompare(catalogNavName(b), "en");
}

export function libraryNavEntries(category: CatalogCategory): CatalogEntry[] {
	if (category === "component") {
		return CATALOG.filter((entry) => entry.category === "component").sort(byNavName);
	}
	if (category === "chart") {
		const lead = CHART_LEAD.map((slug) => CATALOG_BY_SLUG.get(slug)).filter(
			(entry): entry is CatalogEntry => entry !== undefined,
		);
		const rest = CATALOG.filter(
			(entry) => entry.category === "chart" && !CHART_LEAD.includes(entry.slug),
		).sort(byNavName);
		return [...lead, ...rest];
	}
	return BLOCK_LEAD.map((slug) => CATALOG_BY_SLUG.get(slug)).filter(
		(entry): entry is CatalogEntry => entry !== undefined,
	);
}

export function catalogExportName(entry: CatalogEntry): string {
	return entry.exportName;
}

export function catalogImportPath(entry: CatalogEntry): string {
	return entry.importPath;
}

export function catalogBarrelImport(entry: CatalogEntry): string | null {
	if (!entry.hasRootBarrel) {
		return null;
	}
	return `import { ${entry.exportName} } from "@nocoo/basalt";`;
}

export function catalogGranularImport(entry: CatalogEntry): string {
	return `import { ${entry.exportName} } from "${entry.importPath}";`;
}
