import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { createServer } from "vite";
import { loadCatalogFamilyRecords } from "./catalog-content-manifest";

export const GENERATED_RELATIVE_PATH = "src/pages/ui/generated/catalog-page-status.ts";
export const GENERATE_COMMAND = "bun run catalog-page-status:generate";

export type CatalogPageStatus = "ready" | "planned";

interface CatalogEntryShape {
	slug: string;
}

interface CatalogModules {
	entries: readonly CatalogEntryShape[];
	docsBySlug: Readonly<Record<string, unknown>>;
	examplesBySlug: Readonly<Record<string, readonly unknown[] | undefined>>;
}

export function deriveCatalogPageStatuses({
	entries,
	docsBySlug,
	examplesBySlug,
}: CatalogModules): ReadonlyArray<readonly [string, CatalogPageStatus]> {
	const seen = new Set<string>();
	return entries.map((entry) => {
		if (seen.has(entry.slug)) {
			throw new Error(`Duplicate catalog slug: ${entry.slug}`);
		}
		seen.add(entry.slug);
		return [
			entry.slug,
			docsBySlug[entry.slug] && examplesBySlug[entry.slug]?.[0] ? "ready" : "planned",
		] as const;
	});
}

export function renderCatalogPageStatusModule(
	statuses: ReadonlyArray<readonly [string, CatalogPageStatus]>,
): string {
	const lines = statuses.map(([slug, status]) => {
		const key = /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(slug) ? slug : JSON.stringify(slug);
		return `\t${key}: ${JSON.stringify(status)},`;
	});
	return [
		"// Generated by scripts/catalog-page-status.ts. Do not edit.",
		"",
		"export const CATALOG_PAGE_STATUS = {",
		...lines,
		"} as const;",
		"",
	].join("\n");
}

export async function loadCatalogModulesWithVite(repoRoot: string): Promise<CatalogModules> {
	const server = await createServer({
		root: repoRoot,
		configFile: path.join(repoRoot, "vite.config.ts"),
		server: { middlewareMode: true },
		appType: "custom",
		logLevel: "silent",
	});

	try {
		const [catalogModule, docsModule, demosModule, families] = await Promise.all([
			server.ssrLoadModule("/src/pages/ui/catalog.ts"),
			server.ssrLoadModule("/src/pages/ui/docs.ts"),
			server.ssrLoadModule("/src/pages/ui/demos.tsx"),
			loadCatalogFamilyRecords(repoRoot, server),
		]);
		const docsBySlug = {
			...(docsModule.CATALOG_DOCS as Record<string, unknown>),
		};
		const examplesBySlug = {
			...(demosModule.UI_EXAMPLES as Record<string, readonly unknown[] | undefined>),
		};
		for (const { family, record } of families) {
			for (const [slug, content] of Object.entries(record)) {
				if (docsBySlug[slug] || examplesBySlug[slug]) {
					throw new Error(`Catalog content owner collision for "${slug}" with family "${family}"`);
				}
				docsBySlug[slug] = content.docs;
				examplesBySlug[slug] = content.examples;
			}
		}
		return {
			entries: catalogModule.CATALOG as readonly CatalogEntryShape[],
			docsBySlug,
			examplesBySlug,
		};
	} finally {
		await server.close();
	}
}

export async function generateCatalogPageStatusModule(repoRoot: string): Promise<string> {
	const modules = await loadCatalogModulesWithVite(repoRoot);
	return renderCatalogPageStatusModule(deriveCatalogPageStatuses(modules));
}

export function writeCatalogPageStatusFile(filePath: string, expected: string): void {
	mkdirSync(path.dirname(filePath), { recursive: true });
	writeFileSync(filePath, expected);
}

export function checkCatalogPageStatusFile(filePath: string, expected: string): void {
	let actual: string;
	try {
		actual = readFileSync(filePath, "utf8");
	} catch {
		throw new Error(`Catalog page-status manifest is missing. Run \`${GENERATE_COMMAND}\`.`);
	}
	if (actual !== expected) {
		throw new Error(`Catalog page-status manifest is stale. Run \`${GENERATE_COMMAND}\`.`);
	}
}
