import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { createServer, type ViteDevServer } from "vite";

export const FAMILY_DIR_RELATIVE = "src/pages/ui/catalog-content/families";
export const GENERATED_RELATIVE_PATH = "src/pages/ui/generated/catalog-content-family.ts";
export const GENERATE_COMMAND = "bun run catalog-content:generate";

export interface CatalogContentFamilyRecord {
	docs?: unknown;
	examples?: readonly { id?: string }[];
}

export function listCatalogFamilyFiles(repoRoot: string): string[] {
	const dir = path.join(repoRoot, FAMILY_DIR_RELATIVE);
	if (!existsSync(dir)) {
		return [];
	}
	return readdirSync(dir)
		.filter((name) => name.endsWith(".tsx"))
		.sort();
}

export function familyIdFromFile(fileName: string): string {
	return fileName.replace(/\.tsx$/, "");
}

export async function loadCatalogFamilyRecords(
	repoRoot: string,
	server: ViteDevServer,
): Promise<Array<{ family: string; record: Record<string, CatalogContentFamilyRecord> }>> {
	const loaded: Array<{ family: string; record: Record<string, CatalogContentFamilyRecord> }> = [];
	for (const file of listCatalogFamilyFiles(repoRoot)) {
		const family = familyIdFromFile(file);
		const modulePath = `/${FAMILY_DIR_RELATIVE}/${file}`;
		const loadedModule = await server.ssrLoadModule(modulePath);
		const record = loadedModule.default as Record<string, CatalogContentFamilyRecord> | undefined;
		if (!record || typeof record !== "object" || Array.isArray(record)) {
			throw new Error(`catalog content family "${family}" is missing a default record`);
		}
		loaded.push({ family, record });
	}
	return loaded;
}

export function deriveCatalogContentFamily(
	families: Array<{ family: string; record: Record<string, CatalogContentFamilyRecord> }>,
): Array<readonly [string, string]> {
	const owned = new Map<string, string>();
	for (const { family, record } of families) {
		for (const [slug, content] of Object.entries(record)) {
			const previous = owned.get(slug);
			if (previous) {
				throw new Error(`Duplicate catalog content slug "${slug}" in ${previous} and ${family}`);
			}
			if (!content?.docs) {
				throw new Error(`Catalog content family "${family}" is missing docs for "${slug}"`);
			}
			const examples = content.examples;
			if (!examples?.[0]) {
				throw new Error(`Catalog content family "${family}" is missing examples for "${slug}"`);
			}
			const prefix = `${slug}-`;
			for (const example of examples) {
				const id = example.id ?? "";
				if (!id.startsWith(prefix) || id.length <= prefix.length) {
					throw new Error(
						`Catalog content family "${family}" has invalid scenario id "${id}" for "${slug}"`,
					);
				}
			}
			owned.set(slug, family);
		}
	}
	return [...owned.entries()].sort(([left], [right]) => left.localeCompare(right, "en"));
}

export function renderCatalogContentFamilyModule(
	entries: Array<readonly [string, string]>,
): string {
	const lines = entries.map(([slug, family]) => {
		const key = /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(slug) ? slug : JSON.stringify(slug);
		return `\t${key}: ${JSON.stringify(family)},`;
	});
	return [
		"// Generated by scripts/catalog-content-manifest.ts. Do not edit.",
		"",
		"export const CATALOG_CONTENT_FAMILY = {",
		...lines,
		"} as const;",
		"",
	].join("\n");
}

export async function generateCatalogContentFamilyModule(repoRoot: string): Promise<string> {
	const server = await createServer({
		root: repoRoot,
		configFile: path.join(repoRoot, "vite.config.ts"),
		server: { middlewareMode: true },
		appType: "custom",
		logLevel: "silent",
	});
	try {
		const families = await loadCatalogFamilyRecords(repoRoot, server);
		return renderCatalogContentFamilyModule(deriveCatalogContentFamily(families));
	} finally {
		await server.close();
	}
}

export function writeCatalogContentFamilyFile(filePath: string, content: string): void {
	mkdirSync(path.dirname(filePath), { recursive: true });
	writeFileSync(filePath, content);
}

export function checkCatalogContentFamilyFile(filePath: string, expected: string): void {
	if (!existsSync(filePath)) {
		throw new Error(`Catalog content family manifest is missing. Run \`${GENERATE_COMMAND}\`.`);
	}
	const actual = readFileSync(filePath, "utf8");
	if (actual !== expected) {
		throw new Error(`Catalog content family manifest is stale. Run \`${GENERATE_COMMAND}\`.`);
	}
}
