import { render, screen } from "@testing-library/react";
import { describe, expect, it } from "vitest";
import { AreaChart } from "./area";
import { BarChart } from "./bar";
import { BulletChart } from "./bullet";
import { Colors } from "./chart-colors";
import { Charts } from "./charts";
import { CustomChart } from "./custom-chart";
import { DateNavigation } from "./date-navigation";
import { DonutChart } from "./donut";
import { FunnelChart } from "./funnel";
import { Gauge } from "./gauge";
import { GroupedBarChart } from "./grouped-bar";
import { HeatmapCalendar } from "./heatmap-calendar";
import { ItemList } from "./item-list";
import { LineChart } from "./line";
import { CHART_COLORS, ChartPalette } from "./palette";
import { RadarChart } from "./radar";
import { SankeyChart } from "./sankey";
import { SlotBarChart } from "./slot-bar";
import { Sparkline } from "./sparkline";
import { StackedBarChart } from "./stacked-bar";
import { StatCard } from "./stat-card";
import { Timeline } from "./timeline";
import { Timeseries } from "./timeseries";

const points = [{ x: "Mon", y: 4, y2: 2 }];

describe("charts", () => {
	it("keeps the 24-color palette", () => {
		expect(CHART_COLORS).toHaveLength(24);
		render(<ChartPalette />);
		expect(screen.getByRole("img", { name: "Chart colors" })).toBeInTheDocument();
	});

	it("accepts caller data and accessible names", () => {
		render(<LineChart data={points} ariaLabel="Requests" />);
		expect(screen.getByRole("img", { name: "Requests" })).toBeInTheDocument();
		render(<BarChart data={points} ariaLabel="Bars" />);
		expect(screen.getByRole("img", { name: "Bars" })).toBeInTheDocument();
		render(<AreaChart data={points} ariaLabel="Area" />);
		expect(screen.getByRole("img", { name: "Area" })).toBeInTheDocument();
		render(<DonutChart data={[{ name: "A", value: 1 }]} ariaLabel="Share" />);
		expect(screen.getByRole("img", { name: "Share" })).toBeInTheDocument();
		render(<RadarChart data={[{ subject: "Speed", value: 10 }]} ariaLabel="Radar" />);
		expect(screen.getByRole("img", { name: "Radar" })).toBeInTheDocument();
		render(<FunnelChart data={[{ name: "In", value: 10 }]} ariaLabel="Funnel" />);
		expect(screen.getByRole("img", { name: "Funnel" })).toBeInTheDocument();
		render(<BulletChart data={[{ name: "KPI", value: 4, target: 8 }]} ariaLabel="Bullet" />);
		expect(screen.getByRole("img", { name: "Bullet" })).toBeInTheDocument();
		render(<GroupedBarChart data={points} ariaLabel="Grouped" />);
		expect(screen.getByRole("img", { name: "Grouped" })).toBeInTheDocument();
		render(<StackedBarChart data={points} ariaLabel="Stacked" />);
		expect(screen.getByRole("img", { name: "Stacked" })).toBeInTheDocument();
		render(<Sparkline data={points} ariaLabel="Spark" />);
		expect(screen.getByRole("img", { name: "Spark" })).toBeInTheDocument();
		render(<SlotBarChart data={points} ariaLabel="Slots" />);
		expect(screen.getByRole("img", { name: "Slots" })).toBeInTheDocument();
		render(<SankeyChart ariaLabel="Flow" />);
		expect(screen.getByRole("img", { name: "Flow" })).toBeInTheDocument();
		render(<Charts data={points} ariaLabel="Overview" />);
		expect(screen.getByRole("img", { name: "Overview" })).toBeInTheDocument();
		render(<Timeseries data={points} ariaLabel="Series" />);
		expect(screen.getByRole("img", { name: "Series" })).toBeInTheDocument();
		render(<CustomChart data={points} ariaLabel="Custom" />);
		expect(screen.getByRole("img", { name: "Custom" })).toBeInTheDocument();
		render(<Colors />);
		render(<HeatmapCalendar values={[1, 2, 3]} ariaLabel="Heat" />);
		expect(screen.getByRole("img", { name: "Heat" })).toBeInTheDocument();
		render(<ItemList items={[{ label: "A", value: "1" }]} ariaLabel="Workers" />);
		expect(screen.getByRole("list", { name: "Workers" })).toHaveTextContent("A 1");
		render(<Timeline items={[{ title: "Shipped", at: "Tue" }]} ariaLabel="Events" />);
		expect(screen.getByRole("list", { name: "Events" })).toHaveTextContent("Shipped");
		render(<StatCard label="CPU" value="8%" />);
		expect(screen.getByRole("img", { name: "CPU 8%" })).toBeInTheDocument();
		render(<Gauge value={20} ariaLabel="Load" />);
		expect(screen.getByText("Load")).toBeInTheDocument();
		render(<DateNavigation ariaLabel="When" />);
		expect(screen.getByRole("button", { name: "When" })).toBeInTheDocument();
	});
});
